##################################################################################
#         Calls workflow from code repo
##################################################################################
name: Debug - IOS Build

on:
  workflow_dispatch:
  push:
    branches:
      - debug/reusable-ios-build

jobs:
  ios_build:
    uses: IDEMSInternational/open-app-builder/.github/workflows/reusable-ios-build.yml@feat/resusable-ios-build
    secrets: inherit
