name: TestHub Ephemeral Sync & Preview

on:
  workflow_dispatch:
    inputs:
      user_email:
        required: true
        type: string
      webhook_url:
        required: false
        type: string
      webhook_token:
        required: false
        type: string

jobs:
  synced_preview:
    uses: IDEMSInternational/open-app-builder/.github/workflows/reusable-synced-preview.yml@offload-testhub-build
    with:
      user_email: ${{ github.event.inputs.user_email }}
      webhook_url: ${{ github.event.inputs.webhook_url }}
      webhook_token: ${{ github.event.inputs.webhook_token }}
    secrets: inherit
